variable "name_prefix"    { type = string }
variable "vpc_id"         { type = string }
variable "subnet_ids"     { type = list(string) }
variable "ec2_sg_id"      { type = string }
variable "instance_class" { type = string }
variable "db_username"    { type = string }
variable "db_password"    { type = string }
variable "multi_az"       { type = bool }
variable "initial_db_name"{ type = string }